name: CI/CD for Google Cloud Run

on:
  push:
    branches:
      - main # Replace with your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK with google-github-actions/auth
        uses: google-github-actions/auth@v0.6
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate with Service Account
        run: |
          gcloud auth activate-service-account --key-file=${{ secrets.GCP_SA_KEY }}

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/hang-image:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/hang-image:${{ github.sha }}

      - name: Deploy with Terraform
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Get Cloud Run service URL
        id: get-url
        run: |
          URL=$(gcloud run services describe my-hangman-app-3 --format='value(status.url)')
          echo "Service URL: $URL"
          echo "Service URL::$URL" >> $GITHUB_ENV

      - name: Set Output
        run: echo "SERVICE_URL=${{ steps.get-url.outputs.url }}" >> $GITHUB_ENV